// Mock user data for the leaderboard and community features

import type { User, Badge } from "@/types/database";

export interface MockUserWithStats extends User {
  badges: string[];
  stats: {
    termsCreated: number;
    clipsLinked: number;
    comments: number;
    ratioWins: number;
  };
  isTrollDesMonats: boolean;
}

export const MOCK_USERS: MockUserWithStats[] = [
  {
    id: "user-1",
    discord_id: "303835609762627586",
    username: "GleggLord420",
    glegg_score: 6720,
    is_gleggmire: false,
    is_admin: true,
    is_moderator: true,
    is_banned: false,
    joined_at: "2024-06-15T10:00:00Z",
    badges: [
      "first_term",
      "term_master",
      "first_clip",
      "clip_hoarder",
      "first_definition",
      "upvote_magnet",
      "commenter",
      "troll_king",
      "glegg_verified",
      "veteran",
      "linker",
      "high_score",
      "kek_master",
    ],
    stats: {
      termsCreated: 47,
      clipsLinked: 83,
      comments: 312,
      ratioWins: 29,
    },
    isTrollDesMonats: false,
  },
  {
    id: "user-2",
    discord_id: "198273645182736451",
    username: "KanackenKoenig",
    glegg_score: 4210,
    is_gleggmire: false,
    is_admin: false,
    is_moderator: true,
    is_banned: false,
    joined_at: "2024-08-20T14:30:00Z",
    badges: [
      "first_term",
      "term_master",
      "first_clip",
      "first_definition",
      "upvote_magnet",
      "commenter",
      "troll_king",
      "veteran",
      "high_score",
    ],
    stats: {
      termsCreated: 31,
      clipsLinked: 52,
      comments: 198,
      ratioWins: 18,
    },
    isTrollDesMonats: true,
  },
  {
    id: "user-3",
    discord_id: "827364518273645182",
    username: "SnenchMeister",
    glegg_score: 2850,
    is_gleggmire: false,
    is_admin: false,
    is_moderator: false,
    is_banned: false,
    joined_at: "2024-10-05T09:15:00Z",
    badges: [
      "first_term",
      "first_clip",
      "first_definition",
      "upvote_magnet",
      "commenter",
      "cope_lord",
      "high_score",
    ],
    stats: {
      termsCreated: 18,
      clipsLinked: 34,
      comments: 156,
      ratioWins: 12,
    },
    isTrollDesMonats: false,
  },
  {
    id: "user-4",
    discord_id: "736451827364518273",
    username: "CopeLordSupreme",
    glegg_score: 1580,
    is_gleggmire: false,
    is_admin: false,
    is_moderator: false,
    is_banned: false,
    joined_at: "2024-11-12T18:00:00Z",
    badges: [
      "first_term",
      "first_definition",
      "commenter",
      "cope_lord",
      "ratio_survivor",
      "high_score",
    ],
    stats: {
      termsCreated: 9,
      clipsLinked: 15,
      comments: 243,
      ratioWins: 7,
    },
    isTrollDesMonats: false,
  },
  {
    id: "user-5",
    discord_id: "645182736451827364",
    username: "xXClipChimpXx",
    glegg_score: 1120,
    is_gleggmire: false,
    is_admin: false,
    is_moderator: false,
    is_banned: false,
    joined_at: "2025-01-08T12:45:00Z",
    badges: [
      "first_clip",
      "clip_hoarder",
      "first_definition",
      "linker",
      "high_score",
    ],
    stats: {
      termsCreated: 3,
      clipsLinked: 67,
      comments: 45,
      ratioWins: 2,
    },
    isTrollDesMonats: false,
  },
  {
    id: "user-6",
    discord_id: "518273645182736451",
    username: "LungenTorpedo69",
    glegg_score: 780,
    is_gleggmire: false,
    is_admin: false,
    is_moderator: false,
    is_banned: false,
    joined_at: "2025-03-22T20:30:00Z",
    badges: [
      "first_term",
      "first_clip",
      "first_definition",
      "commenter",
      "anonymous_hero",
    ],
    stats: {
      termsCreated: 7,
      clipsLinked: 12,
      comments: 89,
      ratioWins: 5,
    },
    isTrollDesMonats: false,
  },
  {
    id: "user-7",
    discord_id: "273645182736451827",
    username: "RatioGott",
    glegg_score: 420,
    is_gleggmire: false,
    is_admin: false,
    is_moderator: false,
    is_banned: false,
    joined_at: "2025-06-14T16:00:00Z",
    badges: [
      "first_term",
      "first_definition",
      "ratio_survivor",
      "kek_master",
    ],
    stats: {
      termsCreated: 5,
      clipsLinked: 8,
      comments: 134,
      ratioWins: 15,
    },
    isTrollDesMonats: false,
  },
  {
    id: "user-8",
    discord_id: "182736451827364518",
    username: "Neuling2025",
    glegg_score: 85,
    is_gleggmire: false,
    is_admin: false,
    is_moderator: false,
    is_banned: false,
    joined_at: "2025-12-01T11:00:00Z",
    badges: ["first_term", "first_definition"],
    stats: {
      termsCreated: 2,
      clipsLinked: 1,
      comments: 14,
      ratioWins: 0,
    },
    isTrollDesMonats: false,
  },
  {
    id: "user-9",
    discord_id: "364518273645182736",
    username: "SilentWatcher",
    glegg_score: 210,
    is_gleggmire: false,
    is_admin: false,
    is_moderator: false,
    is_banned: false,
    joined_at: "2025-09-18T08:20:00Z",
    badges: ["first_clip", "first_definition", "anonymous_hero"],
    stats: {
      termsCreated: 1,
      clipsLinked: 4,
      comments: 67,
      ratioWins: 1,
    },
    isTrollDesMonats: false,
  },
  {
    id: "user-10",
    discord_id: "451827364518273645",
    username: "GleggVerified",
    glegg_score: 3400,
    is_gleggmire: false,
    is_admin: false,
    is_moderator: true,
    is_banned: false,
    joined_at: "2024-07-30T15:00:00Z",
    badges: [
      "first_term",
      "term_master",
      "first_clip",
      "first_definition",
      "upvote_magnet",
      "glegg_verified",
      "veteran",
      "high_score",
    ],
    stats: {
      termsCreated: 24,
      clipsLinked: 41,
      comments: 102,
      ratioWins: 9,
    },
    isTrollDesMonats: false,
  },
];

export const MOCK_BADGES: Badge[] = MOCK_USERS.flatMap((user) =>
  user.badges.map((badgeType, i) => ({
    id: `badge-${user.id}-${i}`,
    user_id: user.id,
    badge_type: badgeType,
    earned_at: user.joined_at,
  })),
);
